name = "Jade's Server Pack"
author = "jadelily18"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35ea6a1fa80edb3e0260a769f230cd4ebe8c9981fa7bebe78774bb20b40b052a"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
